service: my-service

app: my-service
org: realabbas

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: ap-south-1
functions:
  dictionary:
    handler: handler.dictionary
    events:
      - http:
          path: dictionary
          method: get
  wordExist:
    handler: handler.wordExist
    events:
      - http:
          path: wordExist
          method: get

plugins:
  - serverless-offline
